#!/bin/bash

. test_helper.sh
TIMEOUT=30

if [ "$1" != "wait" ]
then
    export FILTER=${1:-acceptance}
    lein dynamodb-local &
    trap "pkill -f dynamodb-local" EXIT
    wait_for_port 8000 15
    run_test "ordinator.acceptance*" $TIMEOUT $FILTER
else
    lein dynamodb-local run
fi
