#!/bin/bash

export dynamodb_endpoint="http://localhost:${DYNAMODB_PORT:="8082"}"
export AWS_ACCESS_KEY="aws-key"
export AWS_SECRET_KEY="aws-secret"

. test_helper.sh
TIMEOUT=60

run_dynamodb

export FILTER=${1:-persistence}
run_test "ordinator.unit.persistence" $TIMEOUT $FILTER
